name: .NET

on:
  pull_request:
    branches: [ "main" ]
    
env:
  workdir: ./src/

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        working-directory: ${{ env.workdir }}
        run: dotnet restore
      - name: Build
        working-directory: ${{ env.workdir }}
        run: dotnet build --no-restore
      - name: Test
        working-directory: ${{ env.workdir }}
        run: dotnet test --no-build --verbosity normal