name: Create and publish MirageQueue package

env:
  workdir: ./src/MirageQueue/
  DOTNET_VERSION: '8.0.x'

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{secrets.PAT_GITHUB_PUSH}}
          
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
        env:
          DOTNET_INSTALL_DIR: "${{github.workspace}}/.dotnet"
          
      - name: Install Versionize
        run: dotnet tool install --global Versionize
        
      - name: Config github user
        run: |
          git config --global user.name 'Hederson Boechat'
          git config --global user.email 'hederson@users.noreply.github.com'        

      - name: Restore dependencies
        working-directory: ${{ env.workdir }}
        run: dotnet restore
        
      - name: Build
        working-directory: ${{ env.workdir }}
        run: dotnet build --no-restore
        
      - name: Run Versionize
        working-directory: ${{ env.workdir }}
        run: |
          export PATH="$PATH:/home/docker/.dotnet/tools"
          versionize --skip-dirty --aggregate-pre-releases